# Generated by Django 3.2.5 on 2021-08-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_breed_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='dog_size',
            new_name='size',
        ),
    ]
