# Generated by Django 3.2.5 on 2021-08-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_rename_dog_size_breed_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('id',)},
        ),
    ]
