# Generated by Django 3.2.5 on 2021-08-31 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20210820_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='colour',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 15, 14, 55, 171778, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
