# Generated by Django 3.2.5 on 2021-09-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20210901_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='pets.pet'),
        ),
    ]
