# Generated by Django 3.2.5 on 2021-08-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('id',)},
        ),
    ]
