# Generated by Django 3.1.3 on 2021-07-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='profiles.userprofile')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
