# Generated by Django 3.1.3 on 2021-07-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_address',
            new_name='email',
        ),
    ]
