# Generated by Django 3.1.3 on 2021-07-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('contact', '0002_auto_20210729_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='profiles.userprofile'),
        ),
    ]
