# Generated by Django 3.1.3 on 2021-07-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='size',
            field=models.CharField(default='L', max_length=2),
            preserve_default=False,
        ),
    ]
