# Generated by Django 3.1.3 on 2021-08-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_businesshour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshour',
            options={'verbose_name': 'Business Hours', 'verbose_name_plural': 'Business Hours'},
        ),
    ]
