# Generated by Django 3.2.5 on 2021-08-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessHour',
            new_name='Availability',
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availability'},
        ),
    ]
