# Generated by Django 3.2.5 on 2021-08-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_delete_appointment'),
        ('services', '0008_auto_20210807_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('reserved', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='checkout.order')),
            ],
        ),
    ]
