# Generated by Django 3.1.3 on 2021-08-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210810_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
