# Generated by Django 3.2.5 on 2021-08-15 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0014_rename_size_price_dog_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='orders.order'),
        ),
    ]
