# Generated by Django 3.2.5 on 2021-08-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_appointment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='task_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
