# Generated by Django 3.2.5 on 2021-08-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_appointment_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='dog_size',
        ),
        migrations.AddField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default=0.0, max_length=20),
            preserve_default=False,
        ),
    ]
