# Generated by Django 3.2.5 on 2021-08-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20210820_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-end_time',)},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ('-end_time',), 'verbose_name_plural': 'Availability'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('id',)},
        ),
    ]
