# Generated by Django 3.2.5 on 2021-09-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20210905_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='order_lineitem',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='taxi',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service'),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=20, null=True),
        ),
    ]
