# Generated by Django 3.1.3 on 2021-08-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_profile',
        ),
    ]
