# Generated by Django 3.2.5 on 2021-08-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210801_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
