# Generated by Django 3.2.5 on 2021-08-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_orderlineitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='service',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
