# Generated by Django 3.2.5 on 2021-08-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20210815_2330'),
        ('services', '0015_alter_appointment_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
