# Generated by Django 3.2.5 on 2021-08-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_newsletteremail_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterEmail',
        ),
    ]
