# Generated by Django 3.2.5 on 2021-08-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-end_date',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'ordering': ('id',)},
        ),
    ]
